# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.utils import configclass

from isaaclab_tasks.manager_based.manipulation.reach.reach_env_cfg import ReachEnvCfg

from . import mdp

##
# Pre-defined configs
##
from h1_reach.robots import A1_RIGHT_CFG  # isort: skip


##
# Environment configuration
##


@configclass
class H1ReachEnvCfg(ReachEnvCfg):
    def __post_init__(self):
        # post init of parent
        super().__post_init__()

        # switch robot to the A1 right arm
        self.scene.robot = A1_RIGHT_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")
        # override rewards
        self.rewards.end_effector_position_tracking.params["asset_cfg"].body_names = [".*Link7.*"]
        self.rewards.end_effector_position_tracking_fine_grained.params["asset_cfg"].body_names = [".*Link7.*"]
        self.rewards.end_effector_orientation_tracking.params["asset_cfg"].body_names = [".*Link7.*"]
        # override actions
        self.actions.arm_action = mdp.JointPositionActionCfg(
            asset_name="robot", joint_names=[".*joint.*"], scale=0.5, use_default_offset=True
        )
        # replace the cartesian-box pose command with one that samples random joint configs and
        # forward-kinematics them to the end-effector pose. Every target is reachable by construction.
        self.commands.ee_pose = mdp.FkReachablePoseCommandCfg(
            asset_name="robot",
            body_name=".*Link7.*",
            chain=mdp.A1_RIGHT_CHAIN,
            joint_range_scale=0.8,
            resampling_time_range=(4.0, 4.0),
            make_quat_unique=False,
            debug_vis=True,
            # ranges are unused (the command is generated by FK), but the base cfg requires them
            ranges=mdp.FkReachablePoseCommandCfg.Ranges(
                pos_x=(0.0, 0.0),
                pos_y=(0.0, 0.0),
                pos_z=(0.0, 0.0),
                roll=(0.0, 0.0),
                pitch=(0.0, 0.0),
                yaw=(0.0, 0.0),
            ),
        )

        # Reward shaping for joint position+orientation tracking.
        # Keep the two linear penalties for far-range gradient...
        self.rewards.end_effector_position_tracking.weight = -0.5
        self.rewards.end_effector_orientation_tracking.weight = -0.3
        # ...but replace the separate fine-grained terms with multiplicative ones, so the policy
        # only earns the reward when BOTH position and orientation are close (prevents it from
        # maximizing one objective while ignoring the other). Two scales: a coarse term whose basin
        # covers the operating region (provides gradient from far out) and a fine term that sharpens
        # the last few cm/degrees.
        self.rewards.end_effector_position_tracking_fine_grained = None
        self.rewards.end_effector_pose_tracking_coarse = RewTerm(
            func=mdp.pose_command_error_tanh,
            weight=0.5,
            params={
                "asset_cfg": SceneEntityCfg("robot", body_names=[".*Link7.*"]),
                "pos_std": 0.25,
                "ori_std": 0.5,
                "command_name": "ee_pose",
            },
        )
        self.rewards.end_effector_pose_tracking_fine = RewTerm(
            func=mdp.pose_command_error_tanh,
            weight=0.5,
            params={
                "asset_cfg": SceneEntityCfg("robot", body_names=[".*Link7.*"]),
                "pos_std": 0.05,
                "ori_std": 0.1,
                "command_name": "ee_pose",
            },
        )

        # feed the end-effector tracking error (in base frame) into the policy observation, so it
        # can close its own control loop instead of inferring the EE pose from joint angles.
        self.observations.policy.ee_pose_error = ObsTerm(
            func=mdp.ee_pose_error_b,
            params={"asset_cfg": SceneEntityCfg("robot", body_names=[".*Link7.*"]), "command_name": "ee_pose"},
        )


@configclass
class H1ReachEnvCfg_PLAY(H1ReachEnvCfg):
    def __post_init__(self):
        # post init of parent
        super().__post_init__()
        # make a smaller scene for play
        self.scene.num_envs = 50
        self.scene.env_spacing = 2.5
        # disable randomization for play
        self.observations.policy.enable_corruption = False
