# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Pose command that is guaranteed to be reachable.

Instead of sampling a pose in a cartesian box (which may be unreachable for the arm),
this samples a random joint configuration within the joint limits and runs forward
kinematics to obtain the corresponding end-effector pose. Every commanded pose is
therefore reachable in both position and orientation by construction.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import MISSING
from typing import TYPE_CHECKING

import torch

from isaaclab.envs.mdp.commands import UniformPoseCommand, UniformPoseCommandCfg
from isaaclab.utils import configclass
from isaaclab.utils.math import quat_from_matrix

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedEnv


# Kinematic chain of the A1 right arm, in order base_link -> Link1 -> ... -> Link7.
# Each entry is (joint_name_pattern, origin_xyz, origin_rpy). All joint axes are +z.
# Source: h1_reach/assets/urdf/A1/a1_right.urdf
_HALF_PI = math.pi / 2.0
A1_RIGHT_CHAIN = [
    (".*joint1.*", (0.0, 0.0, 0.0315), (0.0, 0.0, 0.0)),
    (".*joint2.*", (0.0, 0.0, 0.12745), (_HALF_PI, _HALF_PI, 0.0)),
    (".*joint3.*", (0.0, -0.09325, 0.0), (_HALF_PI, -_HALF_PI, 0.0)),
    (".*joint4.*", (0.0, 0.001, 0.14025), (-_HALF_PI, 0.0, 0.0)),
    (".*joint5.*", (0.0, -0.088, -0.001), (_HALF_PI, 0.0, 0.0)),
    (".*joint6.*", (0.0, -0.0005, 0.133), (_HALF_PI, 0.0, 0.0)),
    (".*joint7.*", (0.0, 0.112, -0.0005), (_HALF_PI, 0.0, math.pi)),
]


def _rpy_to_matrix(roll: float, pitch: float, yaw: float) -> torch.Tensor:
    """URDF fixed-axis rpy -> rotation matrix R = Rz(yaw) @ Ry(pitch) @ Rx(roll)."""
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    rx = torch.tensor([[1, 0, 0], [0, cr, -sr], [0, sr, cr]], dtype=torch.float32)
    ry = torch.tensor([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]], dtype=torch.float32)
    rz = torch.tensor([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]], dtype=torch.float32)
    return rz @ ry @ rx


class FkReachablePoseCommand(UniformPoseCommand):
    """Pose command generated by forward kinematics of a random joint configuration."""

    cfg: FkReachablePoseCommandCfg

    def __init__(self, cfg: FkReachablePoseCommandCfg, env: ManagerBasedEnv):
        super().__init__(cfg, env)
        # resolve the chain joint indices in kinematic order (not articulation order)
        self._chain_joint_ids: list[int] = [self.robot.find_joints(pat)[0][0] for pat, _, _ in cfg.chain]
        # precompute the fixed origin transforms (4x4) for each joint, on device
        origins = torch.eye(4, dtype=torch.float32).repeat(len(cfg.chain), 1, 1)
        for i, (_, xyz, rpy) in enumerate(cfg.chain):
            origins[i, :3, :3] = _rpy_to_matrix(*rpy)
            origins[i, :3, 3] = torch.tensor(xyz, dtype=torch.float32)
        self._origins = origins.to(self.device)  # (num_joints, 4, 4)

    def _fk(self, q: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Return Link7 FK in the base frame using Isaac Lab's native quaternion layout (beta2: xyzw)."""
        n = q.shape[0]
        t = torch.eye(4, device=self.device).expand(n, 4, 4).contiguous()
        rz = torch.eye(4, device=self.device).expand(n, 4, 4).contiguous()
        for i in range(len(self._chain_joint_ids)):
            c, s = torch.cos(q[:, i]), torch.sin(q[:, i])
            rz[:, 0, 0], rz[:, 0, 1] = c, -s
            rz[:, 1, 0], rz[:, 1, 1] = s, c
            t = t @ self._origins[i].unsqueeze(0) @ rz
        return t[:, :3, 3], quat_from_matrix(t[:, :3, :3])

    def _resample_command(self, env_ids: Sequence[int]):
        # joint limits for the chain joints (assume identical across envs)
        limits = self.robot.data.joint_pos_limits.torch[0, self._chain_joint_ids]  # (num_joints, 2)
        lower, upper = limits[:, 0], limits[:, 1]
        # optionally shrink toward the center of the range
        center = 0.5 * (lower + upper)
        half = 0.5 * (upper - lower) * self.cfg.joint_range_scale
        lower, upper = center - half, center + half
        # sample random reachable joint configs and FK to the end-effector pose
        n = len(env_ids)
        q = lower + (upper - lower) * torch.rand(n, len(self._chain_joint_ids), device=self.device)
        pos, quat = self._fk(q)
        self.pose_command_b[env_ids, :3] = pos
        self.pose_command_b[env_ids, 3:] = quat


@configclass
class FkReachablePoseCommandCfg(UniformPoseCommandCfg):
    """Configuration for the FK-based reachable pose command."""

    class_type: type = FkReachablePoseCommand

    chain: list = MISSING
    """Kinematic chain: list of (joint_name_pattern, origin_xyz, origin_rpy), in base->ee order."""

    joint_range_scale: float = 1.0
    """Fraction of each joint's full range to sample from (centered). 1.0 = full range."""
